Parameters:
  ParamInstanceType:
    Type: String
    Default: t2.micro
    AllowedValues: 
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
    Description: AWS::EC2::Instance
  KeyName:
    Description: Name of an EC2 KeyPair to enable SSH access to the instance.
    Type: 'AWS::EC2::KeyPair::KeyName'
    ConstraintDescription: must be the name of an existing EC2 KeyPair.
Resources:
  RdboxhqEc2InstanceVpnServer:
    Type: 'AWS::EC2::Instance'
    DeletionPolicy: "Delete"
    Properties:
      ImageId: ami-09c81ecf1c2b2ef70
      InstanceType:
        Ref: ParamInstanceType
      BlockDeviceMappings: 
        - DeviceName: "/dev/sda1"
          Ebs: 
            VolumeSize: "20"
      NetworkInterfaces:
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: !ImportValue ExpRdboxhqSubnet
          GroupSet:
            - !ImportValue ExpRdboxhqSecurityGroup
      KeyName: !Ref KeyName
      UserData: !Base64 
        'Fn::Join':
          - ''
          - - |
              #!/bin/bash -xe
            - |
              export DEBIAN_FRONTEND=noninteractive
              apt-mark hold grub-pc
              apt -y update
            - |
              apt -y install ansible bridge-utils traceroute dnsutils
              apt -y install python-pip
              pip install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-latest.tar.gz
              chmod +x /usr/local/init/ubuntu/cfn-hup
              ln -s /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
            - |+
      Tags:
        - Key: Name
          Value:
            RdboxhqEc2InstanceVpnServer
  # EIPAssociation
  RdboxhqEIPVpnServerAssociation:
    Type: 'AWS::EC2::EIPAssociation'
    DeletionPolicy: "Delete"
    Properties:
      AllocationId: !ImportValue ExpRdboxhqEIPVpnServerAllocationId
      InstanceId: !Ref RdboxhqEc2InstanceVpnServer